rabbit:
  image: macintoshplus/rabbitmq-management
  hostname: rabbit
  ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "15671:15671"
    - "15672:15672"
  environment:
    - RABBITMQ_DEFAULT_USER=tqll
    - RABBITMQ_DEFAULT_PASS=toortoor
