version: '3'

services:
  jaegertracing:
    image: jaegertracing/all-in-one:1.6
    #network_mode: host
    restart: "no"
    #volumes:
      # - ./bin:/app/bin
      # - ./log:/app/log
    ports:
      - 5775:5775/udp 
      - 6831:6831/udp 
      - 6832:6832/udp 
      - 5778:5778 
      - 16686:16686 
      - 14268:14268 
      - 9411:9411 
